// src/features/ai/lib/chat.ts
//
// "Chat with your notes" — answers questions using hybrid search
// (semantic + keyword + metadata re-ranking) to retrieve relevant blocks.
// Phase 4 adds: cross-note connection pass + rolling conversation summary.

import { hybridSearch }    from "@/features/ai/lib/search/hybrid"
import {
  callPrimary,
  promptPrimary,
  type ProviderMessage,
  type AICallError,
} from "@/features/ai/lib/client"
import {
  getAllAISummaries,
  getAIHistory,
  appendAIHistory,
  getSurroundingBlocks,
  getConversationSummary,
  saveConversationSummary,
} from "@/features/notes/db/queries"
import type { Note } from "@/types"

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ChatMessage {
  id:        string
  role:      "user" | "assistant"
  content:   string
  createdAt: number
}

export interface RelatedNote {
  title:  string
  noteId: string
}

export interface ChatResult {
  answer:         string
  sourceTitles:   string[]
  sourceNoteIds:  string[]
  usedEmbeddings: boolean
  confidence:     "high" | "low"
  relatedNotes:   RelatedNote[]   // cross-note connection pass results
}

export interface StreamingChatOptions {
  onChunk:  (token: string) => void
  onDone?:  () => void
  onError?: (err: AICallError) => void  // PATCH: changed from Error to AICallError
}

// ─── Token budget ─────────────────────────────────────────────────────────────

const MAX_CONTEXT_CHARS = 12_000

function enforceTokenBudget(chunks: string[]): string[] {
  let total = 0
  const result: string[] = []
  for (const chunk of chunks) {
    if (total + chunk.length > MAX_CONTEXT_CHARS) break
    result.push(chunk)
    total += chunk.length
  }
  return result
}

// ─── Parent context expansion ─────────────────────────────────────────────────

async function expandWithSurroundingBlocks(
  results: Awaited<ReturnType<typeof hybridSearch>>
): Promise<Map<string, string>> {
  const expanded = new Map<string, string>()
  await Promise.allSettled(
    results.map(async (r) => {
      try {
        const surrounding = await getSurroundingBlocks(r.block_id, r.note_id, 2)
        if (surrounding.length > 0) {
          expanded.set(r.block_id, surrounding.join("\n"))
        }
      } catch { /* use original plaintext as fallback */ }
    })
  )
  return expanded
}

// ─── Rolling session memory ───────────────────────────────────────────────────
// Uses last 6 exchanges + a compressed summary of older context.
// The summary is generated by the LLM and stored in ai_conversation_summary.

async function buildHistoryBlock(noteId: string): Promise<string> {
  const [history, summaryRow] = await Promise.all([
    getAIHistory(noteId),
    getConversationSummary(noteId),
  ])

  const parts: string[] = []

  if (summaryRow?.summary) {
    parts.push(`Summary of earlier conversation:\n${summaryRow.summary}`)
  }

  if (history.length > 0) {
    const lines = history.map((h) =>
      `${h.role === "user" ? "User" : "Assistant"}: ${h.content.slice(0, 400)}`
    )
    parts.push(`Recent conversation:\n${lines.join("\n")}`)
  }

  return parts.length > 0 ? `\n${parts.join("\n\n")}\n` : ""
}

/**
 * After history is pruned, generate a rolling summary of the dropped messages.
 * Called asynchronously — doesn't block the response.
 */
async function updateRollingSummary(
  noteId:          string,
  droppedContent:  string,
  existingSummary: string | null,
): Promise<void> {
  try {
    const prompt = existingSummary
      ? `You are summarizing a conversation for context compression.
Existing summary: ${existingSummary}

New messages to incorporate:
${droppedContent}

Write a concise updated summary (max 3 sentences) capturing the key topics discussed.
Summary:`
      : `Summarize this conversation in 2-3 sentences, capturing the key topics:
${droppedContent}
Summary:`

    // Rolling summary is a background processing task — routes through processing slot
    const { promptProcessing } = await import("@/features/ai/lib/client")
    const summary = await promptProcessing(prompt)

    const currentRow = await getConversationSummary(noteId)
    await saveConversationSummary(
      noteId,
      summary.trim(),
      (currentRow?.message_count ?? 0) + droppedContent.split("\n").length
    )
  } catch { /* summary generation is best-effort, never blocks */ }
}

// ─── Cross-note connection pass ───────────────────────────────────────────────

async function findRelatedNotes(
  answerText:    string,
  citedNoteIds:  Set<string>,
  currentNoteId: string | undefined
): Promise<RelatedNote[]> {
  try {
    const query = answerText.slice(0, 500)
    if (!query.trim()) return []

    const results = await hybridSearch(query, 5, { currentNoteId })

    const seen    = new Set<string>()
    const related: RelatedNote[] = []

    for (const r of results) {
      if (citedNoteIds.has(r.note_id)) continue
      if (r.note_id === currentNoteId)  continue
      if (seen.has(r.note_id))          continue
      if (r.final_score < 0.005)        continue

      seen.add(r.note_id)
      related.push({ title: r.note_title, noteId: r.note_id })

      if (related.length >= 3) break
    }

    return related
  } catch {
    return []
  }
}

// ─── Summary fallback ─────────────────────────────────────────────────────────

function scoreByKeyword(query: string, title: string, summary: string): number {
  const q      = query.toLowerCase()
  const words  = q.split(/\s+/).filter((w) => w.length > 2)
  const target = `${title} ${summary}`.toLowerCase()
  return words.reduce((acc, word) => acc + (target.includes(word) ? 1 : 0), 0)
}

async function buildSummaryFallbackContext(
  query:    string,
  allNotes: Note[]
): Promise<{ context: string; sourceTitles: string[]; sourceNoteIds: string[] }> {
  const summaryMap = await getAllAISummaries()
  if (summaryMap.size === 0) {
    return {
      context:       "(No summaries stored yet. Ask the AI to summarize some notes first.)",
      sourceTitles:  [],
      sourceNoteIds: [],
    }
  }

  const scored = allNotes
    .filter((n) => summaryMap.has(n.id))
    .map((note) => ({
      note,
      summary: summaryMap.get(note.id)!,
      score:   scoreByKeyword(query, note.title, summaryMap.get(note.id)!),
    }))
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 5)

  if (scored.length === 0) {
    return {
      context:       "(No notes closely matched this query.)",
      sourceTitles:  [],
      sourceNoteIds: [],
    }
  }

  const lines = scored.map(
    (r) => `Note: "${r.note.title}"\nSummary: ${r.summary}`
  )
  return {
    context:       `Relevant notes from your vault:\n${lines.join("\n\n")}`,
    sourceTitles:  scored.map((r) => r.note.title),
    sourceNoteIds: scored.map((r) => r.note.id),
  }
}

// ─── Context builder ──────────────────────────────────────────────────────────

async function buildChatContext(
  query:        string,
  allNotes:     Note[],
  currentNote?: Note
): Promise<{
  prompt:         string
  sourceTitles:   string[]
  sourceNoteIds:  string[]
  usedEmbeddings: boolean
  confidence:     "high" | "low"
}> {
  let vaultContext   = ""
  let sourceTitles:  string[] = []
  let sourceNoteIds: string[] = []
  let usedEmbeddings = false
  let topScore       = 0

  try {
    const results = await hybridSearch(query, 8, {
      currentNoteId: currentNote?.id,
    })

    if (results.length > 0) {
      usedEmbeddings = true
      topScore       = results[0]?.final_score ?? results[0]?.rrf_score ?? 0

      const seenNoteIds = new Set<string>()
      for (const r of results) {
        if (!seenNoteIds.has(r.note_id)) {
          seenNoteIds.add(r.note_id)
          sourceTitles.push(r.note_title)
          sourceNoteIds.push(r.note_id)
        }
      }

      const expansions     = await expandWithSurroundingBlocks(results)
      const rawChunks      = results.map((r, i) => {
        const text = expansions.get(r.block_id) ?? r.plaintext
        return `[${i + 1}] From "${r.note_title}":\n${text}`
      })
      const budgetedChunks = enforceTokenBudget(rawChunks)
      vaultContext = `Relevant excerpts from your notes:\n\n${budgetedChunks.join("\n\n")}`
    }
  } catch { /* fall through to summary fallback */ }

  if (!usedEmbeddings) {
    const fallback = await buildSummaryFallbackContext(query, allNotes)
    vaultContext   = fallback.context
    sourceTitles   = fallback.sourceTitles
    sourceNoteIds  = fallback.sourceNoteIds
  }

  let currentNoteBlock = ""
  if (currentNote) {
    currentNoteBlock = `\nNote you're currently viewing:\nTitle: ${currentNote.title}\nContent: ${(currentNote.plaintext ?? "").slice(0, 1500)}`
  }

  const confidence: "high" | "low" =
    !usedEmbeddings || topScore < 0.1 ? "low" : "high"

  const prompt = `You are a knowledgeable assistant with access to the user's personal notes vault.
Answer the user's question using ONLY the provided note excerpts as your source.
If the excerpts don't contain enough information to answer, say so honestly — do not guess.
Cite sources by referencing the excerpt numbers like [1] or [2] where relevant.
Be concise and direct.
${vaultContext}
${currentNoteBlock}

User question: ${query}

Answer:`

  return { prompt, sourceTitles, sourceNoteIds, usedEmbeddings, confidence }
}

// ─── Streaming chat (primary path) ───────────────────────────────────────────

export async function streamChatWithNotes(
  query:       string,
  allNotes:    Note[],
  noteId:      string,
  currentNote: Note | undefined,
  streaming:   StreamingChatOptions
): Promise<Omit<ChatResult, "answer">> {
  const historyBlock = await buildHistoryBlock(noteId)
  const ctx          = await buildChatContext(query, allNotes, currentNote)

  const promptWithHistory = ctx.prompt.replace(
    "User question:",
    `${historyBlock}User question:`
  )

  // Build messages array for the primary slot call
  const messages: ProviderMessage[] = [
    { role: "user", content: promptWithHistory },
  ]

  let assembled = ""

  try {
    // callPrimary returns the full response — streaming is a UI concern handled
    // by the caller via onChunk. For true streaming, ChatPanel.tsx should call
    // the provider SDK directly; for now we complete and deliver in one chunk.
    const result = await callPrimary(messages)
    assembled    = result.text

    // Deliver the full response as a single chunk so onChunk contract is met
    streaming.onChunk(assembled)

    // Persist history
    await appendAIHistory(noteId, "user",      query)
    await appendAIHistory(noteId, "assistant", assembled)

    // Update rolling summary asynchronously — don't block the response
    const history = await getAIHistory(noteId)
    if (history.length >= 6) {
      const existingRow  = await getConversationSummary(noteId)
      const droppedLines = [
        `User: ${query}`,
        `Assistant: ${assembled.slice(0, 300)}`,
      ].join("\n")
      updateRollingSummary(noteId, droppedLines, existingRow?.summary ?? null)
    }

    streaming.onDone?.()
  } catch (err: unknown) {
    // The thrown value is already an AICallError from client.ts
    streaming.onError?.(err as AICallError)
  }

  // Cross-note connection pass — run after answer is assembled
  const citedNoteIds = new Set(ctx.sourceNoteIds)
  const relatedNotes = await findRelatedNotes(assembled, citedNoteIds, currentNote?.id)

  return {
    sourceTitles:   ctx.sourceTitles,
    sourceNoteIds:  ctx.sourceNoteIds,
    usedEmbeddings: ctx.usedEmbeddings,
    confidence:     ctx.confidence,
    relatedNotes,
  }
}

// ─── Non-streaming fallback ───────────────────────────────────────────────────

export async function chatWithNotes(
  query:        string,
  allNotes:     Note[],
  noteId:       string,
  currentNote?: Note
): Promise<ChatResult> {
  const historyBlock = await buildHistoryBlock(noteId)
  const ctx          = await buildChatContext(query, allNotes, currentNote)

  const promptWithHistory = ctx.prompt.replace(
    "User question:",
    `${historyBlock}User question:`
  )

  const answer = await promptPrimary(promptWithHistory)

  await appendAIHistory(noteId, "user",      query)
  await appendAIHistory(noteId, "assistant", answer)

  const citedNoteIds = new Set(ctx.sourceNoteIds)
  const relatedNotes = await findRelatedNotes(answer, citedNoteIds, currentNote?.id)

  return { answer, ...ctx, relatedNotes }
}